version: "3.9"

services:
  db:
    image: veyselozaslan/sis-project-postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: studentpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sis_network

  app:
    image: veyselozaslan/sis-project-app:latest
    container_name: cpp_app_container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: studentdb
      DB_USER: studentuser
      DB_PASSWORD: studentpass
    networks:
      - sis_network

volumes:
  postgres_data:

networks:
  sis_network:

